### ISSUE TITLE
Pretrained weight not working for upscaling of x2

### ISSUE THREAD

**Issue by nisargshah1999** [Lornatang/SRGAN-PyTorch#10]
When I tried to run the test_image.py with --upscale-factor 2, I got an error pointing 
    images = torch.cat([bicubic, sr], dim=-1)
RuntimeError: Sizes of tensors must match except in dimension 3. Got 256 and 512 in dimension 2 (The offending index is 1)
Could you please suggest a solution to solve this.

**Comment by Lornatang** [comment]
@nisargshah1999 Hah. I pass it. My command is 
```bash
python3 test_image.py -a srgan_2x2 --lr lr.png --upscale-factor 2 --pretrained --gpu 0
```

**Comment by nisargshah1999** [comment]
ok, solved I was using -a srgan so error.
Thanks
