### ISSUE TITLE
lpips_vgg weight

### ISSUE THREAD

**Issue by JennySeidenschwarz** [Lornatang/SRGAN-PyTorch#11]
Hello everyone :)
thanks a lot for the repo! Training the PSNR part worked well. However, when training the GAN I had problems, because of a missing lpips_vgg.pth file. Maybe I oversee something, but I can't find it. 
Would be nice if you could help me out here!
Best, 
Jenny

**Comment by Lornatang** [comment]
In `weights` dir.
