### ISSUE TITLE
Training dataset structure

### ISSUE THREAD

**Issue by dokluch** [Lornatang/SRGAN-PyTorch#17]
Hi!

How should I structure my training dataset in order for this implementation to work?
Also, what does IMAGE_SIZE refer to? Why the default is 96?

Thank you

**Comment by Lornatang** [comment]
Reference from origin paper [Photo-Realistic Single Image Super-Resolution Using a Generative Adversarial
Network](https://openaccess.thecvf.com/content_cvpr_2017/papers/Ledig_Photo-Realistic_Single_Image_CVPR_2017_paper.pdf)

```text
# 3.2
3.2. Training details and parameters
We trained all networks on a NVIDIA Tesla M40 GPU using a random sample of 350 thousand images from the ImageNet database [44]. These images are distinct from the testing images. We obtained the LR images by downsampling the HR images (BGR, C = 3) using bicubic kernel with downsampling factor r = 4. For each mini-batch we crop 16 random 96 × 96 HR sub images of distinct training images. Note that we can apply the generator model to images of arbitrary size as it is fully convolutional. For optimization we use Adam [35] with β1 = 0.9. 
```

**Comment by Lornatang** [comment]
Reference from origin paper [Photo-Realistic Single Image Super-Resolution Using a Generative Adversarial
Network](https://openaccess.thecvf.com/content_cvpr_2017/papers/Ledig_Photo-Realistic_Single_Image_CVPR_2017_paper.pdf)

```text
# 3.2
3.2. Training details and parameters
We trained all networks on a NVIDIA Tesla M40 GPU
using a random sample of 350 thousand images from the
ImageNet database [44]. These images are distinct from the
1https://github.com/xiph/daala (commit: 8d03668)
2https://github.com/jbhuang0604/SelfExSR
3http://cv.snu.ac.kr/research/DRCN/
4https://twitter.box.com/s/
lcue6vlrd01ljkdtdkhmfvk7vtjhetog
5https://github.com/david-gpu/srez
testing images. We obtained the LR images by downsampling the HR images (BGR, C = 3) using bicubic kernel
with downsampling factor r = 4. For each mini-batch we
crop 16 random 96 × 96 HR sub images of distinct training
images. Note that we can apply the generator model to
images of arbitrary size as it is fully convolutional. For
optimization we use Adam [35] with β1 = 0.9. 
```

**Comment by dokluch** [comment]
> Reference from origin paper [Photo-Realistic Single Image Super-Resolution Using a Generative Adversarial Network](https://openaccess.thecvf.com/content_cvpr_2017/papers/Ledig_Photo-Realistic_Single_Image_CVPR_2017_paper.pdf)
> 
> ```
> # 3.2
> 3.2. Training details and parameters
> We trained all networks on a NVIDIA Tesla M40 GPU using a random sample of 
> 350 thousand images from the ImageNet database [44]. These images are distinct
>  from the testing images. We obtained the LR images by downsampling the HR 
> images (BGR, C = 3) using bicubic kernel with downsampling factor r = 4. For 
> each mini-batch we crop 16 random 96 × 96 HR sub images of distinct training 
> images. Note that we can apply the generator model to images of arbitrary size 
> as it is fully convolutional. For optimization we use Adam [35] with β1 = 0.9. 
> ```

Thank you. As for the structure, I've also figured out I have to name the folders train and test, not train and valid (for DIV2k)
