### ISSUE TITLE
backward Error

### ISSUE THREAD

**Issue by lutianhao** [Lornatang/SRGAN-PyTorch#19]
ssh://tianhao.lu@172.18.33.37:22/data/tianhao.lu/software/anaconda3/envs/GAN/bin/python -u /home/tianhao.lu/.pycharm_helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 0.0.0.0 --port 40739 --file /data/tianhao.lu/code/ProjectArchitecture/complete/SRGAN_demo.py
已连接到 pydev 调试器(内部版本 211.6693.115)# generator parameters: 734219
# discriminator parameters: 5215425
  0%|                                                     | 0/5 [00:06<?, ?it/s]
Traceback (most recent call last):
  File "/home/tianhao.lu/.pycharm_helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/tianhao.lu/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/data/tianhao.lu/code/ProjectArchitecture/complete/SRGAN_demo.py", line 98, in <module>
    g_loss.backward()
  File "/data/tianhao.lu/software/anaconda3/envs/GAN/lib/python3.7/site-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/data/tianhao.lu/software/anaconda3/envs/GAN/lib/python3.7/site-packages/torch/autograd/__init__.py", line 100, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 1024, 1, 1]] is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
python-BaseException

**Comment by lutianhao** [comment]
my torch and torchvision version is 1.5.0 & 0.6.0

**Comment by Lornatang** [comment]
This reason is because the gradient is not conducted during the generator training process. Check if you use `.detach()` below?

**Comment by lutianhao** [comment]
no I didn't , I did not change the model just change the path. I success in one server but in another it doesn't work......

**Comment by Lornatang** [comment]
Can you give me your command? I check it.

**Comment by lutianhao** [comment]
Finally it worked.... I just degrade the version of Pytorch and I don't know why  LOL

**Comment by Lornatang** [comment]
I use PyTorch 1.8.1.
