### ISSUE TITLE
Where's the weight file?

### ISSUE THREAD

**Issue by yunseokddi** [Lornatang/SRGAN-PyTorch#2]
Hello, I'm interested in the field of super resolution, so I'm looking your code.
My GPU is not good, so I want to get pre-trained weight.
Can I install the weight file?

**Comment by Lornatang** [comment]
I've trained. I haven't uploaded yet

**Comment by yunseokddi** [comment]
OK! I shall be waiting for you. Thx

**Comment by Lornatang** [comment]
@yunseokddi some pre-trained in here

**Comment by nisargshah1999** [comment]
Where is the weight file, same issue

**Comment by Lornatang** [comment]
@nisargshah1999 See v0.1.0 package.
