### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'DIR/test'

### ISSUE THREAD

**Issue by kritika1029** [Lornatang/SRGAN-PyTorch#20]
Facing this issue while running the following command- python3 test_benchmark.py -a srgan --pretrained --gpu 0 DIR

FileNotFoundError: [Errno 2] No such file or directory: 'DIR/test'

**Comment by Lornatang** [comment]
You should prepare the test data set and put it in the `DIR/test` directory.
