### ISSUE TITLE
Code doesn't work

### ISSUE THREAD

**Issue by ADharaUTEXAS123007** [Lornatang/SRGAN-PyTorch#25]
[ WARNING ] Directory `/glb/hou/pt.sgs/data/ml_ai_us/4d/usadh7/github_repos/SRGAN-PyTorch/benchmarks` already exists!
[ INFO ] TestingEngine:
[ INFO ] Use GPU: 0 for testing.
[ INFO ] Using pre-trained model `srgan`.
[ INFO ] Load testing dataset.
/glb/hou/pt.sgs/data/ml_ai_us/4d/csoftware/miniconda3/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py:477: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
[ INFO ] Dataset information:
	Path:              /glb/hou/pt.sgs/data/ml_ai_us/4d/usadh7/github_repos/SRGAN-PyTorch/./data/test
	Number of samples: 0
	Number of batches: 0
	Shuffle:           False
	Sampler:           None
	Workers:           8
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "test_benchmark.py", line 167, in <module>
    main()
  File "test_benchmark.py", line 82, in main
    main_worker(args.gpu, args)
  File "test_benchmark.py", line 149, in main_worker
    print(f"MSE       {total_mse_value / len(dataloader):6.4f}\n"
ZeroDivisionError: float division by zero

**Comment by Lornatang** [comment]
Do you check the dataset? It may be caused by an improperly configured data set directory.
