### ISSUE TITLE
Different patch size

### ISSUE THREAD

**Issue by CatalinOAlexandru** [Lornatang/SRGAN-PyTorch#32]
Hi, I'm wondering if you experimented with different patch sizes besides the 96px one. This one works fine, but if I try anything else it will throw errors.

If the patch size is smaller than 96 (this example is 28) then I usually get:
`** On entry to SGEMM  parameter number 10 had an illegal value
Traceback (most recent call last):
  File "train.py", line 283, in <module>
    main()
  File "train.py", line 175, in main
    train_gan(epoch)
  File "train.py", line 246, in train_gan
    d_loss_real = adv_criterion(netD(target), real_label)
  File "/home/calexand/env/srpy/lib/python3.8/site-packages/torch/nn/modules/module.py", li$
    return forward_call(*input, **kwargs)
  File "/home/calexand/defTest/srpy/srgan_pytorch/model.py", line 124, in forward
    out = self.classifier(out)
  File "/home/calexand/env/srpy/lib/python3.8/site-packages/torch/nn/modules/module.py", li$
    return forward_call(*input, **kwargs)
  File "/home/calexand/env/srpy/lib/python3.8/site-packages/torch/nn/modules/container.py",$
    input = module(input)
  File "/home/calexand/env/srpy/lib/python3.8/site-packages/torch/nn/modules/module.py", li$
    return forward_call(*input, **kwargs)
  File "/home/calexand/env/srpy/lib/python3.8/site-packages/torch/nn/modules/linear.py", li$
    return F.linear(input, self.weight, self.bias)
  File "/home/calexand/env/srpy/lib/python3.8/site-packages/torch/nn/functional.py", line 1$
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling cublasSgemm( handle, ople, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

If the patch is bigger, for example 192:
`Traceback (most recent call last):
  File "train.py", line 418, in <module>
    main()
  File "train.py", line 215, in main
    allLossD,allLossG = train_gan(epoch)
  File "train.py", line 315, in train_gan
    d_loss.backward()
  File "/home/calexand/env/srpy/lib/python3.8/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/calexand/env/srpy/lib/python3.8/site-packages/torch/autograd/__init__.py", line 147, in backward
    Variable._execution_engine.run_backward(
RuntimeError: Function AddmmBackward returned an invalid gradient at index 1 - got [32, 18432] but expected shape compatible with [32, 73728]`

**Comment by CatalinOAlexandru** [comment]
For the second error looks like the problem comes from [L122](https://github.com/Lornatang/SRGAN-PyTorch/blob/master/srgan_pytorch/model.py#L112) in the model.py where you multiply 512*6*6. 

In the paper, they only say that it should be a dense layer from 512 to 1024. Changing this to 'nn.Linear(512, 1024)' won't solve the problem, and I'm not sure where to look to fix it.

**Comment by Lornatang** [comment]
image size equal 96 * 96?

**Comment by CatalinOAlexandru** [comment]
Yes. Image size cant be changed for testing purposes.

**Comment by Lornatang** [comment]
What is your current image size during training? What is the test size?

**Comment by CatalinOAlexandru** [comment]
My images are 2200x2200. Changing “image-size” from 96 to for example 28 or 160 will result in the above errors.
The same happens for DIV2K. I believe the problem is from L112 from model.py

**Comment by Lornatang** [comment]
I currently have no problem when testing the code, just make sure the image input is 96*96. In addition, when you make an error, do you mean that it appeared in the training GAN stage?

**Comment by CatalinOAlexandru** [comment]
I am trying to change the 96x96 to something else like 160x160. That change will give the error in Gan, yes

**Comment by Lornatang** [comment]
160 size change `nn.Linear(512 * 6 * 6, 1024)` to `nn.Linear(512 * 10 * 10, 1024)`. It is OK.
Paper set 96 * 96 image resolution size

**Comment by CatalinOAlexandru** [comment]
Yes, I figured that. I want to make it work now based on --image-size parameter, but it has some memory leaking issues. I am still wondering if there is a better way to do it because in the paper they don't use torch.flatten() or multiplying by 6 * 6 or 10* 10

**Comment by Lornatang** [comment]
As same as `torch.view()`, but `torch.flatten()` is too simple~

**Comment by Lornatang** [comment]
It seems that the problem has been resolved, if you have other problems, you can open the problem later.
