### ISSUE TITLE
Pre-trained model dataset

### ISSUE THREAD

**Issue by sebastian-berndt** [Lornatang/SRGAN-PyTorch#33]
Hey! 
I was playing around with your solution and was positively surprised that there is a pre-trained model included. I set everything up and tried to verify your results for Set5. I used the test.py. Sadly the results are rather mediocre:
**0.png:**
MSE       0.0209
RMSE      0.1445
PSNR       16.80
SSIM      0.6989
LPIPS     0.3019
GMSD      0.1458

**2.png:**
MSE       0.0020
RMSE      0.0444
PSNR       27.05
SSIM      0.7365
LPIPS     0.1433
GMSD      0.0778

**3.png**
MSE       0.0058
RMSE      0.0765
PSNR       22.33
SSIM      0.8100
LPIPS     0.1888
GMSD      0.0901

**4.png:**
MSE       0.0058
RMSE      0.0763
PSNR       22.35
SSIM      0.4969
LPIPS     0.2875
GMSD      0.0887

Image 1 gave an error.

What dataset is the pre-trained model trained with? Do you have any idea why I got so bad results?

Anyway, cool model and thanks for your work:)

**Comment by Lornatang** [comment]
I can't understand the problem you describe for the time being.

**Comment by Nakkhatra** [comment]
@Lornatang Hey, the pretrained weights link is actually containing images only, no weights! Can you re-check?

**Comment by Lornatang** [comment]
The next version will usher in a major update, when you can use the latest pre-trained model! @Nakkhatra

**Comment by Lornatang** [comment]
The new version weight has been uploaded, and some known bugs have been fixed @Nakkhatra @sebastian-berndt
