### ISSUE TITLE
DIV2K数据集的格式是什么样的呢-

### ISSUE THREAD

**Issue by Jackson-LIMU** [Lornatang/SRGAN-PyTorch#34]
运行您的命令下载不了DIV2K训练集，如下图
![1628397388(1)](https://user-images.githubusercontent.com/75259876/128620952-df77d184-1b11-42e4-b731-49e6fecee818.png)
请问训练集的目录文件格式应该是什么样的呢？

**Comment by Jackson-LIMU** [comment]
还有，Test的百度云链接挂了

**Comment by Lornatang** [comment]
en. I fix

**Comment by Lornatang** [comment]
没有`wget`下载工具肯定不可以下载，你直接点击链接下载。

**Comment by Lornatang** [comment]
@Jackson-LIMU You can see the README.md in the data directory, where there is a detailed description of the DIV2K data set directory format
