### ISSUE TITLE
 "create_dataset_for_kernelGAN.py"                     

### ISSUE THREAD

**Issue by robomike** [Lornatang/SRGAN-PyTorch#4]
When following the documentation in https://github.com/Lornatang/SRGAN-PyTorch/tree/master/data the command 
 "create_dataset_for_kernelGAN.py"  throws an error:

                    File "create_dataset_for_kernelGAN.py", line 46
    lr_dir = f"./{args.upscale_factor}x/input"
                                             ^

**Comment by robomike** [comment]
updated to Python3

**Comment by Lornatang** [comment]
@robomike Yes, this one needs Python 3 to run.
