### ISSUE TITLE
Errors when SR near to white colors

### ISSUE THREAD

**Issue by SirSykon** [Lornatang/SRGAN-PyTorch#41]
Hello,

I've applied your model to images containing white and yellow sections. The SR results shows green instead of yellow but the strangest is the white color is replaced by a patron I suspect is provoked by storing NaN or something like that. I attach two examples.
With the provided weights:

![white_p](https://user-images.githubusercontent.com/31393313/140304959-253d95ae-30dc-436e-af13-a3b3f5fec806.png)
![yellow_p](https://user-images.githubusercontent.com/31393313/140304962-c868c9aa-6e8f-427d-93ec-f910eb4f08c9.png)

After fine tuning with images from the same dataset:
![white](https://user-images.githubusercontent.com/31393313/140304357-57470204-022f-4702-8a46-f3df808a54e2.png)
![yellow](https://user-images.githubusercontent.com/31393313/140304368-56451d16-608e-4e88-9111-25b7a7c20f52.png)

Any ideas how to fix it?

**Comment by Lornatang** [comment]
I'll see the error, wait a minute

**Comment by SirSykon** [comment]
Any update? I'm intrigued about why the model fails with that kind of images. :)

**Comment by Lornatang** [comment]
I am sorry.~ Input and output range and RGB or BGR?

**Comment by SirSykon** [comment]
RGB. Should it be BGR?

**Comment by Lornatang** [comment]
no, RGB。

**Comment by Lornatang** [comment]
In the near future, I will update the model weights, you can try again later.

**Comment by Lornatang** [comment]
@SirSykon Try to pull the latest code.
