### ISSUE TITLE
D(SR) = 0 and D(HR) = 1

### ISSUE THREAD

**Issue by valentin-fngr** [Lornatang/SRGAN-PyTorch#46]
Hi, 

I have been training the SRGAN model from the repo and I have got the following losses : 

![image](https://user-images.githubusercontent.com/42917280/153715485-41ea9a9f-72ba-4005-aed5-ebf36fc236ce.png)

I do not understand why D(SR) = 0 over the epochs and D(HR) = 1. 
The dataset that I used is the ImageNet dataset provided in the readme. Is the generator unable to trick the discriminator ? 

Thank you very much

**Comment by Lornatang** [comment]
This is also the case for me during training, usually a common problem when training original GANs.

**Comment by valentin-fngr** [comment]
Should I still expect some good results ? 
Or do I need to investigate on how to fix it ?

**Comment by Lornatang** [comment]
You need to wait patiently for the training results and choose the best one.

**Comment by Lornatang** [comment]
Thank you.

**Comment by rhtm02** [comment]
Are you saying that you are learning several times to find the optimal model or that you are learning to the end and finding the optimal model among them?

**Comment by valentin-fngr** [comment]
> 

I think he meant wait till the end of the training process. Surprisingly, your model can perform badly during a lot of iterations and then, suddenly, you will see the D(SR) increase and the D(HR) decrease, which is what you want. You just need to be patient due to the instability of GAN training :(

**Comment by Lornatang** [comment]
Currently I am trying to improve the training of SRGAN to make it more stable

**Comment by Lornatang** [comment]
From the current point of view, the training of GAN still has the problem of "model collapse", and it may be necessary to find the best model from the training node of GAN

**Comment by rhtm02** [comment]
Ok thx a lot

**Comment by valentin-fngr** [comment]
> Currently I am trying to improve the training of SRGAN to make it more stable

How many iterations do you use to train your model ? 
I would be interested in knowing what approaches you are going to use to make the training more stable as I am really interested in the subject

**Comment by Lornatang** [comment]
For example these methods 
[WassterinGAN](https://github.com/Lornatang/WassersteinGAN-PyTorch)
[WassterinGAN_GP](https://github.com/Lornatang/WassersteinGAN_GP-PyTorch)

**Comment by Lornatang** [comment]
I will not update on this library though, as this library is the closest implementation to the original paper
