### ISSUE TITLE
requirements.txt is missing tensorboard and setuptools

### ISSUE THREAD

**Issue by valentin-fngr** [Lornatang/SRGAN-PyTorch#47]
Hi, 

Correct me if I am wrong, but I needed to install tensorboard version **2.8.0** and setuptools **59.5.0**
Not a big deal, but it was not in the requirements.txt. 
I might be wrong with that, just wanted to ask

**Comment by Lornatang** [comment]
At present, PyTorch is best matched with setuptools==29.5.0, and TensorBoard can be installed according to the latest version. I will update later, thanks for the reminder.
