### ISSUE TITLE
train does not generate weights

### ISSUE THREAD

**Issue by robomike** [Lornatang/SRGAN-PyTorch#5]
Hi,

I successfully have run train.py, but there is no .pth "weights file" generated at all.  How may we generate the weights file?

Mike

**Comment by Lornatang** [comment]
@robomike 
First of all, please make sure that your directory is generated `weights`.
Each epoch then generates a weight file。

**Comment by robomike** [comment]
Hi @Lornatang There is a Weights folder
![image](https://user-images.githubusercontent.com/4317367/110271833-c4e38880-7f96-11eb-9c78-8b43f82ee3ef.png)
There are no generated weights:
![image](https://user-images.githubusercontent.com/4317367/110271857-d2990e00-7f96-11eb-946f-1c2cb49bbdff.png)
There are results
![image](https://user-images.githubusercontent.com/4317367/110271898-e6447480-7f96-11eb-92b6-dd797385f532.png)

So how come there are no weights?

**Comment by Lornatang** [comment]
@robomike Can you tell me your execution order?

**Comment by robomike** [comment]
@Lornatang After downloading the DIV2k dataset , per the readme i execute the train.py

**Comment by Lornatang** [comment]
I don't seem to have generated the results folder.

**Comment by Lornatang** [comment]
@robomike This error is fixed.
