### ISSUE TITLE
Modify the upscale_factor param

### ISSUE THREAD

**Issue by nguyendung1612** [Lornatang/SRGAN-PyTorch#50]
when I reduce the upscale_factor value to 2 or 3, I had the problem at classifier layer. I used the DIV2K dataset. Can you help me to fix it? 

Thank you!
![error](https://user-images.githubusercontent.com/43613837/162647504-294e376e-877e-4cf4-93c4-76f6b353c907.png)

**Comment by Lornatang** [comment]
This error seems to be caused by the discriminator, please check if the discriminator input image scale is 128x128.

**Comment by nguyendung1612** [comment]
The input image scale is 192x192

**Comment by nguyendung1612** [comment]
> This error seems to be caused by the discriminator, please check if the discriminator input image scale is 128x128.

The input image scale is 192x192

**Comment by Lornatang** [comment]
Change `model.py` 108 line to `nn.Linear(512 * 6 * 6, 1024),`.

**Comment by Lornatang** [comment]
You may need to adjust the discriminator model architecture based on your input image size.
If you input image size equal `128x128`, change `model.py` 108 line to `nn.Linear(512 * 6 * 6, 1024),`.
If you input image size equal `192x192`, change `model.py` 108 line to `nn.Linear(512 * 12 * 12, 1024),`.
