### ISSUE TITLE
Validation Error in loading state_dict for Generator

### ISSUE THREAD

**Issue by hurkal** [Lornatang/SRGAN-PyTorch#52]
Hi. I got this error message while validating on Colab:

```
RuntimeError: Error(s) in loading state_dict for Generator:
	Missing key(s) in state_dict: "conv_block1.0.weight", "conv_block1.0.bias", "conv_block1.1.weight", "trunk.0.rcb.0.weight", "trunk.0.rcb.1.weight", "trunk.0.rcb.1.bias", 
     ... 
     "upsampling.1.upsample_block.0.bias", "upsampling.1.upsample_block.2.weight", "conv_block3.weight", "conv_block3.bias". 
	Unexpected key(s) in state_dict: "epoch", "best_psnr", "state_dict", "optimizer", "scheduler". 
```

Tries to use this weight file: **SRGAN_x4-ImageNet-2204c839.pth.tar** as provided in the link

To overcome the error, updated the code;
`model.load_state_dict(checkpoint["state_dict"])`
to
`model.load_state_dict(checkpoint["state_dict"],False)`
in validate.py on line 34.

After changing, validation works but PSNR is only 8.89dB. I tried also all weight files of SRGAN in the link but all 3 of them have the same PSNR result: 8.89

![baby](https://user-images.githubusercontent.com/11699111/163480056-9d400261-2f95-4024-aa77-4d3726f4205c.png)

Which point have I missed?

**Comment by Lornatang** [comment]
I'm very sorry, this should be my weight upload error, please click the link again to download the latest weight.

**Comment by hurkal** [comment]
Thank you very much for this project and quick answer.
