### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by leminhhuy132** [Lornatang/SRGAN-PyTorch#55]
why when i want to calculate psnr during training i get this error even though the batch_size config is very small?

Load all datasets successfully.
Build SRResNet model successfully.
Define all loss functions successfully.
Define all optimizer functions successfully.
Check whether the pretrained model is restored...
Epoch: [1][   0/1989]	Time 15.878 (15.878)	Data  0.000 ( 0.000)	Loss 0.267222 (0.267222)
Traceback (most recent call last):
  File "train_srresnet.py", line 463, in <module>
    main()
  File "train_srresnet.py", line 98, in main
    train_loss = train(model, train_prefetcher, pixel_criterion, optimizer, epoch, scaler, writer, psnr_model, ssim_model)
  File "train_srresnet.py", line 249, in train
    scaler.scale(loss).backward()
  File "/usr/local/lib/python3.7/dist-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/__init__.py", line 175, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA out of memory. Tried to allocate 288.00 MiB (GPU 0; 14.76 GiB total capacity; 11.70 GiB already allocated; 123.75 MiB free; 13.22 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by Lornatang** [comment]
What is the size of your image? Observe the fluctuation of the CUDA memory during the operation of the program.

**Comment by Lornatang** [comment]
The PSNR model is small and fast, it shouldn't take up so much memory, can you tell me the memory usage with and without PSNR?

**Comment by leminhhuy132** [comment]
When i comment psnr in train function, cuda memory as shown below
![Screenshot from 2022-06-10 09-36-40](https://user-images.githubusercontent.com/77653557/172979264-ea66e444-9d59-404a-b3dd-ffb646ee7b8e.png)

**Comment by Lornatang** [comment]
Does this issue occur during training or during testing?

**Comment by Lornatang** [comment]
train() or validate()？

**Comment by leminhhuy132** [comment]
only in train()

**Comment by Lornatang** [comment]
CUDA version?
CUDNN version?
PyTorch & Torchvision version?

**Comment by Lornatang** [comment]
In the current code, the psnr calculation will not be called, but will be called in validate(), check the difference between some native code and the latest code on Git?

**Comment by leminhhuy132** [comment]
CUDA 11.1
CUDNN 8.0.5
Pytorch 1.11.0+cu113
Torchvision 0.12.0+cu113
I run this in gg colab

**Comment by leminhhuy132** [comment]
yes, but i don't know why when i call train() it gives error

**Comment by Lornatang** [comment]
give me your config.py file. I check it

**Comment by leminhhuy132** [comment]
I edit your code in this repo, please help me check it
git@github.com:leminhhuy132/SRGAN_DACN.git

**Comment by Lornatang** [comment]
> I edit your code in this repo, please help me check it [git@github.com](mailto:git@github.com):leminhhuy132/SRGAN_DACN.git

in config.py 46 line batch_size 256? lt is so big?

**Comment by leminhhuy132** [comment]
i tried batch_size 16, it still got error

**Comment by Lornatang** [comment]
There may be multiple tasks running on the machine at the same time, or the machine may not have enough memory
