### ISSUE TITLE
upscale_factor has no effect

### ISSUE THREAD

**Issue by eformx** [Lornatang/SRGAN-PyTorch#56]
I changed upscale_factor = 2 in config.py
I run inferernce.py and results are upscaled by 4.
How can I pass in an upscale_factor of 2 in inference.py?

**Comment by Lornatang** [comment]
OK, you need to modify two places.
1- Change `config.py` 31 line `upscale_factor = 4` to **`upscale_factor = 2`**
2- Change `model.py` 139 line `for _ in range(2):` to **`for _ in range(1):`**

**Comment by Lornatang** [comment]
So, `inferernce.py` should use X2 model weights, if you use X4 model weights, maybe it is bad~

**Comment by Lornatang** [comment]
This library gives X4 times the model, which cannot be directly used for X2 inference, you can try to load some model weights

**Comment by eformx** [comment]
Will this work or is there a better one:
Discriminator_x2-DFO2K-e37ff529.pth.tar
