### ISSUE TITLE
AttributeError: module 'config' has no attribute 'feature_model_extractor_node'

### ISSUE THREAD

**Issue by zjgt** [Lornatang/SRGAN-PyTorch#58]
Hi, I just tried this and ran into a problem. The error seems to refer to the config file:
    feature_model_extractor_node = "features.35"  #line 87 in the config file. Do I miss something in my package?
Thanks!

(srgan) D:\SRGAN-PyTorch-main>python train_srgan.py
Load all datasets successfully.
Build SRGAN model successfully.
Traceback (most recent call last):
  File "D:\SRGAN-PyTorch-main\train_srgan.py", line 581, in <module>
    main()
  File "D:\SRGAN-PyTorch-main\train_srgan.py", line 48, in main
    content_criterion, adversarial_criterion = define_loss()
  File "D:\SRGAN-PyTorch-main\train_srgan.py", line 255, in define_loss
    content_criterion = ContentLoss(config.feature_model_extractor_node,
AttributeError: module 'config' has no attribute 'feature_model_extractor_node'

**Comment by Lornatang** [comment]
If you train SRGAN network, you should change `config.py` 33 line.
```python
# mode = "train_srresnet"
mode = "train_srgan"
```
