### ISSUE TITLE
Error while training data

### ISSUE THREAD

**Issue by santosh-shriyan** [Lornatang/SRGAN-PyTorch#6]
I am trying to train data using one of the specified dataset (Div2k_valid_HR). 
I have unzipped the Div2k dataset in the data folder as mentioned in the readme.md including train and val folders as it was mentioned i the training example. There were a number of errors including a error on non-extent test folder in data folder, so I created one.
I got his error.

![Capture2](https://user-images.githubusercontent.com/63632331/111022210-646da480-83f7-11eb-98a6-c651b2aeef41.PNG)

**Comment by santosh-shriyan** [comment]
After which just at random I added an image to this test folder and I am able to train the targeted number of epochs but get this error.

![Capture](https://user-images.githubusercontent.com/63632331/111022230-823b0980-83f7-11eb-97cd-918cde1e35c8.PNG)
![Capture1](https://user-images.githubusercontent.com/63632331/111022231-82d3a000-83f7-11eb-9215-19f71968deca.PNG)

**Comment by Lornatang** [comment]
@santosh-shriyan The error appears to be an image size discrepancy.
Can you print all image shape? Check it?

**Comment by santosh-shriyan** [comment]
I am using the standard datasets that you provided in the readme (Div2k) and moved to the train and val folders as mentioned in the script file. 
The image in the SRGAN-PyTorch-master/data/test folder is a 300x300 jpg image attached below.
![taj](https://user-images.githubusercontent.com/63632331/111116356-eb538600-858b-11eb-9fd6-69de0ff427c6.jpg)

I actually haven't bee able to understand your code so I am not sure about how I can check the image shape.

**Comment by Lornatang** [comment]
You can
```python
from PIL import Image
img = Image.open("{YOUR image path}")
print(img.size)  # Check it..
```
