### ISSUE TITLE
pretrained models

### ISSUE THREAD

**Issue by junghyun-avikus** [Lornatang/SRGAN-PyTorch#64]
What are the dataset that the uploaded pretrained weights trained on?
I directly used weights from the google drive to inference some of my images,
but they seem to have minor effects only.

Are there still room to improve if I train the model?
If so, do you recommend train them from scratch or start from the pretrained weights?

**Comment by Lornatang** [comment]
Because the pre-trained model is only degraded by simple and ideal bicubic interpolation.
But，do not worry，I created some useful methods to face real world images, See [BSRGAN](https://github.com/Lornatang/BSRGAN-PyTorch) and [Real_ESRGAN](https://github.com/Lornatang/Real_ESRGAN-PyTorch)
