### ISSUE TITLE
TypeError: unsupported operand type(s) for |

### ISSUE THREAD

**Issue by AnSMru** [Lornatang/SRGAN-PyTorch#66]
Traceback (most recent call last):
  File "test.py", line 23, in <module>
    from image_quality_assessment import PSNR, SSIM
  File "/SRGAN-PyTorch/image_quality_assessment.py", line 205, in <module>
    def _get_mscn_feature(image: np.ndarray) -> list[float | Any]:
TypeError: unsupported operand type(s) for |: 'type' and '_SpecialForm'

What to do?

**Comment by huchi00057** [comment]
I have same question!

**Comment by huchi00057** [comment]
You can create a new virtual environment in python 3.10

**Comment by huchi00057** [comment]
After recreate the environment (python = 3.10), my problem had been solved!

**Comment by huchi00057** [comment]
![image](https://user-images.githubusercontent.com/46515944/216803825-3739912b-b597-491f-8af4-71ee500ec604.png)

Reference： https://github.com/tiangolo/typer/issues/371

**Comment by AnSMru** [comment]
I use Jetson TX2, and I can only 3.6 with cuda

**Comment by Lornatang** [comment]
change `np.ndarray` to `np.ndarray | Any`

**Comment by charleneguillaumot** [comment]
Hello, your last suggestion does not work for me Lornatang

**Comment by Lornatang** [comment]
@charleneguillaumot Perhaps you can remove the definition of the type~

**Comment by jiwonchoi99** [comment]
Anyone solve this problem without upgrading the python version?
@Lornatang I'm not sure what the 'remove the definition of the type~' means.
