### ISSUE TITLE
Multi-GPU training on local device

### ISSUE THREAD

**Issue by momalave** [Lornatang/SRGAN-PyTorch#7]
Hi Lornatang,
   How can I train on 2 GPUs on my local device. For example, device 3 and 4 only ? When I use os.environ["CUDA_VISIBLE_DEVICES"]="3,4" it gives me an error.

"RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!"

Please help. 

Thanks!

**Comment by Lornatang** [comment]
--gpu 3,4

**Comment by momalave** [comment]
I get this error:

Photo-Realistic Single Image Super-Resolution Using a Generative Adversarial Network.: error: argument --gpu: invalid int value: '3,4'

**Comment by Lornatang** [comment]
This example uses all GPU devices or a single GPU device by default..

**Comment by momalave** [comment]
I see, I was hoping to just use a subset of the GPUs on node. I wonder if
there is a work around for doing this? I will look into this.

Thanks,
momalave

**Comment by Lornatang** [comment]
Yeah. Wait.... I found..

**Comment by momalave** [comment]
Great! Can you please share how to do this? Thanks :-).

**Comment by Lornatang** [comment]
You can use `.to("cuda:3,4") replace .cuda(3,4)`.
It is OK.
