### ISSUE TITLE
The amp

### ISSUE THREAD

**Issue by Jihnjockey** [Lornatang/SRGAN-PyTorch#70]
![image](https://user-images.githubusercontent.com/53632794/217737628-8e932fe0-f307-44c9-b5cb-966cf5ce1d31.png)
![image](https://user-images.githubusercontent.com/53632794/217737687-17a9f331-a8c3-4e88-8dfb-524555d06770.png)
Why do you delete the  amp related funcions? Don't you need automatic mixing precision anymore？

**Comment by Lornatang** [comment]
No， there is a problem of disappearing weights

**Comment by Jihnjockey** [comment]
Can you elaborate on it？I don‘t understand the "disappearing weights". Thank you very much.

**Comment by Lornatang** [comment]
Maybe vanishing gradient problem
