### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by charleneguillaumot** [Lornatang/SRGAN-PyTorch#71]
Hello, I have this error when running the test.py file. I do not know how to fix it. 
![image](https://user-images.githubusercontent.com/19189088/217846473-d989a832-9911-4588-b116-85b7893e0049.png)

Thanks in advance for your help

**Comment by Lornatang** [comment]
Please check if you have correctly installed the version of the PyTorch that support CUDA~
