### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'torch._C._TensorMeta' and 'type'

### ISSUE THREAD

**Issue by Satyajit1993** [Lornatang/SRGAN-PyTorch#74]
Hello Lorna

I am getting an error message in image_quality_assessment.py, line 584,

 kernel: torch.Tensor | tuple,
TypeError: unsupported operand type(s) for |: 'torch._C._TensorMeta' and 'type'

Kindly Help.

**Comment by Lornatang** [comment]
I can't judge exactly how this problem arises, guess it may be a return type problem, try to remove the return type?

**Comment by Satyajit1993** [comment]
Are you able to run the code without any error?

After removing the unsupported operand many other errors are arising


Kindly help by telling your environment cuda cudnn pytorch

**Comment by Lornatang** [comment]
I run in Ubuntu22.04, no error.

**Comment by linnnn1** [comment]
请问您解决这个问题了吗？我遇到了同样的问题

**Comment by kartikchhipa** [comment]
> TypeError: unsupported operand type(s) for |: 'torch._C._TensorMeta' and 'type'

Use Python >=3.10 This would solve this problem
