### ISSUE TITLE
Testing time

### ISSUE THREAD

**Issue by nisargshah1999** [Lornatang/SRGAN-PyTorch#8]
Thanks for the code,

when I use CPU inference time is less compared to GPU while testing the model.
Could you help me understand why such a thing is happening?

Code for reference,

Just change in line 109,
    with torch.no_grad():
        c_time = time.time()
        sr = model(lr)
        print('Total time is %f sec.'%(time.time()- c_time))

**Comment by nisargshah1999** [comment]
For your reference,

For CPU inference time is 0.387750 sec and for GPU it is 0.699459 sec

> Thanks for the code,
> 
> when I use CPU inference time is less compared to GPU while testing the model.
> Could you help me understand why such a thing is happening?
> 
> Code for reference,
> 
> Just change in line 109,
> with torch.no_grad():
> c_time = time.time()
> sr = model(lr)
> print('Total time is %f sec.'%(time.time()- c_time))

**Comment by Lornatang** [comment]
@nisargshah1999 Easy, because GPU benefits most from parallelism, can you try to process 32 or 64 images together? How can we infer?
