### ISSUE TITLE
Train Code

### ISSUE THREAD

**Issue by GeekerLeone** [Lornatang/SRGAN-PyTorch#85]
![image](https://github.com/Lornatang/SRGAN-PyTorch/assets/67179306/14006ebe-d612-4921-909d-a2007766bb68)
I notice that you specify 'g_optimizer' as discriminator optimizer and 'd_optimizer' is not used during training model. I want to make sure whether it is a mistake or not.

**Comment by Lornatang** [comment]
You're right. It's a mistake.
