### ISSUE TITLE
Unable to reproduce the result of SRGAN_x4-SRGAN_ImageNet.pth.tar

### ISSUE THREAD

**Issue by chenhsiu48** [Lornatang/SRGAN-PyTorch#86]
Hi, 

I followed the instructions to train SRResNet first (90 epochs) and then SRGAN (18 epochs). However, I can not reproduce the result of SRGAN_x4-SRGAN_ImageNet.pth.tar. The result I get is a very blurry image. Can you give me some clues? 
Why do I need to download DiscriminatorForVGG_x4-SRGAN_ImageNet.pth.tar? Use it as pretrain model for SRGAN?

**Comment by Fanzzzd** [comment]
I trained SRResNet model without pre-trained data. Then I used this model to generate a new image then I get some results like one this:
![sr_comic](https://github.com/Lornatang/SRGAN-PyTorch/assets/71874435/677c6a83-759c-4d51-9cb6-df965c865a33)

**Comment by Lornatang** [comment]
There is currently an optimizer bug, which has been fixed
